import "./globals.css";
import Navbar from "@/components/Header";
import { ContactUsForm } from "@/components/ContactUsForm";
import Footer from "@/components/Footer";
import { services } from "@/components/ServiceSection";
import { AuthProvider } from "@/context/AuthContext";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" className="overflow-auto">
      <body
        className={` antialiased`}
      >
        <Navbar services={services}/>
        <AuthProvider>{children}</AuthProvider>
        
        <Footer services={services}/>
      </body>
    </html>
  );
}
