import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Header";
import { ContactUsForm } from "./components/ContactUsForm";
import Footer from "./components/Footer";
import { services } from "./components/ServiceSection";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" className="overflow-auto">
      <body
        className={` antialiased`}
      >
        <Navbar services={services}/>
        {children}
        <ContactUsForm/>
        <Footer services={services}/>
      </body>
    </html>
  );
}
