import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Header";
import { ContactUsForm } from "./components/ContactUsForm";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Navbar/>
        {children}
        <ContactUsForm/>
      </body>
    </html>
  );
}
